### ISSUE TITLE
Error: sklearn distribution not found

### ISSUE THREAD

**Issue by ja-Reeve** [nowling-lab/asaph#9]
I just downloaded your package and 'sklearn' on my laptop, but I'm running into an error when I try to run `asaph_pca`:
`File "/Users/james/opt/anaconda3/envs/sklearn-env/lib/python3.12/site-packages/pkg_resources/__init__.py", line 870, in _resolve_dist
    raise DistributionNotFound(req, requirers)
**pkg_resources.DistributionNotFound: The 'sklearn' distribution was not found and is required by asaph**`

I've tried your debugging with pip, but it seems that 'sklearn' is deprecated:
<img width="944" alt="Screenshot 2024-02-14 at 17 47 15" src="https://github.com/nowling-lab/asaph/assets/82411887/af819b67-d084-40cc-91d8-b8d15d42a7de">

I've tried installing 'scikit-learn' but the error presists.

**Comment by rnowling** [comment]
Fixed by PR #10

**Comment by rnowling** [comment]
Fixed by PR #10
